### ISSUE TITLE
LICENSE file does not give terms of use

### ISSUE THREAD

**Issue by kms15** [bwrc/edf#1]
The license file only contains the author and copyright date, but does not provide any license for use.  If you are willing to add either an open source license (such as an MIT or GPL license) or a statement that you are not granting a permissive license (e.g. "all rights reserved, please contact author for licensing information if you wish to use this code."), this additional text would make it much easier for an end user to know whether and how he or she can use your code.

**Comment by aheneliu** [comment]
Hi! In accordance with how R packages are structured (https://cran.r-project.org/doc/manuals/r-release/R-exts.html) the license for the package is mentioned in the License-field in the file DESCRIPTION. I have now also updated the readme to include a mentioning of the license. The EDF-package is licensed under the MIT license.

**Comment by kms15** [comment]
Excellent - thanks!  I did not know to look in the DESCRIPTION file, but now I do, and including the license in the README file will make it much easier for the next person to find (and basically addresses my concerns).  

Although it's now less of an issue, I still find it a bit confusing to have a LICENSE file that does not contain a copy of the license.  From the link you sent, it looks like this is not recommended style for R-packages: in section 1.1.2 it states "The optional file LICENSE/LICENCE contains a copy of the license of the package. To avoid any confusion only include such a file if it is referred to in the ‘License’ field of the DESCRIPTION file. "  Now that the license is given in the readme, however, I think your intent is clear enough that you could leave it as it is if you prefer.

**Comment by aheneliu** [comment]
Hi!

Returning to the somewhat confusing way of including licenses in R packages :)

As mentioned on the last line of section 1.1.2 in 
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Licensing

"A few “standard” licenses are rather license templates which need additional information to be completed via ‘+ file LICENSE’. "

The MIT license is one of these, and according to
https://www.r-project.org/Licenses/MIT
one must in this case create the file LICENSE with the contents of YEAR and COPYRIGHT HOLDEr, and refer to the license as "MIT + file LICENSE".
