### ISSUE TITLE
Timestamp on signal

### ISSUE THREAD

**Issue by frankmyhre** [bwrc/edf#2]
Hi @aheneliu,

I using the edfReader, to extract signales from the .EDF-file, and so far I've been able to get all values from eg the saturation signal. 
Is it possible to also get the Timestamp, so that I can see exactly when data was recorded?

Best regards
Frank

**Comment by aheneliu** [comment]
Hi!

If you are using the `edf`-package to read EDF-signals, then you can proceed as follows. 

First read the data
    `library(edf)`
    `datafile <- "/tmp/signal.edf"`
    `recording <- read.edf(datafile)`
after which the start and stop timestamps can be found in the global EDF header, which you can view as follows:
    `str(recording$header.global)`

You can then use the fields `timestamp.start`and `timestamp.stop`, i.e., `recording$header.global$timestamp.start`.

Hope this helps!
